site_name: 鹤翔万里的笔记本
site_url: https://note.tonycrane.cc/
repo_url: https://github.com/TonyCrane/note/
edit_uri: tree/master/docs
site_description: 鹤翔万里（TonyCrane）的笔记本
copyright: Copyright &copy; 2022 <a href="https://github.com/TonyCrane"  target="_blank" rel="noopener">TonyCrane</a>

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking # 在url中使用标题定位锚点
    - navigation.tabs
    # - navigation.indexes # nav栏隐藏index
    # - navigation.sections # nav节点缩进
    # - navigation.expand # 不折叠左侧nav节点
    - navigation.top # 一键回顶部
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  palette:
    - scheme: default
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - attr_list
  - md_in_html
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TonyCrane/
    - icon: fontawesome/solid/rss
      link: https://blog.tonycrane.cc/
    - icon: fontawesome/solid/home
      link: https://tonycrane.cc/
  analytics:
    provider: custom
    property: G-DYETCPM289

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - css/tasklist.css
  - css/custom.css

extra_javascript:
  # - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - js/katex.js
  # - js/scheme.js # this is in template 'base.html'

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true

nav:
  - Home:
    - HomePage: index.md
    - TODO: todo.md
  - Computer Science:
    - Programming Language:
      - C/C++: cs/pl/c_cpp.md
      - Haskell: cs/pl/haskell.md
  - CTF:
    - QRCode: ctf/qrcode.md
  - Writeups:
    - Hackergame 2021: writeups/hackergame2021.md

