site_name: 鹤翔万里的笔记本
site_url: https://note.tonycrane.cc/
repo_name: TonyCrane/note
repo_url: https://github.com/TonyCrane/note/
edit_uri: tree/master/docs
site_description: 鹤翔万里（TonyCrane）的笔记本
copyright: Copyright &copy; 2022 <a href="https://github.com/TonyCrane"  target="_blank" rel="noopener">TonyCrane</a>

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  palette:
    - scheme: default

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TonyCrane/
    - icon: fontawesome/solid/rss
      link: https://blog.tonycrane.cc/
    - icon: fontawesome/solid/home
      link: https://tonycrane.cc/
  analytics:
    provider: custom
    property: G-DYETCPM289

extra_css:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - css/tasklist.css
  - css/custom.css
  - css/card.css

extra_javascript:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - js/katex.js
  # js/scheme.js # this is in template 'base.html'

plugins:
  - rss
  - search
  - encryptcontent:  # now just for one page, need to be improved
      title_prefix: "🔒 "
      summary: '🔒 AAA School Bus Writeups'
      placeholder: '在此输入密码     '
      decryption_failure_message: '密码错误'
      encryption_info_message: '请输入密码查看本篇文章（请联系我）'
      remember_password: True 
      default_expire_dalay: 48
      encrypted_something:
        mkdocs-encrypted-toc: [nav, class]
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true

nav:
  - Home:
    - index.md
  - Computer Science:
    - cs/index.md
    - 编程语言:
      - cs/pl/index.md
      - C/C++: cs/pl/c_cpp.md
      - Haskell: cs/pl/haskell.md
      - x86 汇编语言: cs/pl/asm.md
      - RISC-V ISA: cs/pl/riscv.md
    - 计算机系统:
      - cs/system/index.md
      - 计算机系统 I:
        - cs/system/cs1/index.md
        - 数据的表示: cs/system/cs1/topic1.md
        - 数字逻辑电路基础: cs/system/cs1/topic2.md
        - 组合逻辑电路设计: cs/system/cs1/topic3.md
        - 时序逻辑电路设计: cs/system/cs1/topic4.md
        - 指令集体系结构: cs/system/cs1/topic5.md
        - 处理器: cs/system/cs1/topic6.md
    - 网络相关:
      - cs/web/index.md
      - SVG: cs/web/svg.md
      - log4j 漏洞复现: cs/web/log4j_vuln.md
    - 正则表达式: cs/regex.md
    - Unicode: cs/unicode.md
  - CTF:
    - ctf/index.md
    - 隐写术:
      - ctf/steg/index.md
      - 图片隐写: ctf/steg/image.md
      - 音频隐写: ctf/steg/audio.md
    - 沙箱逃逸: 
      - ctf/escapes/index.md
      - Python 沙箱逃逸: ctf/escapes/pysandbox.md
    - 编码与密码: ctf/coding.md
    - QRCode: ctf/qrcode.md
    - Esolang: ctf/esolang.md
  - Writeups:
    - writeups/index.md
    - Training:
      - Ethernaut: writeups/ethernaut.md
      - Security Innovation: writeups/SecurityInnovation.md
      - AAA School Bus: writeups/AAA.md
    - "2021":
      - SYSU MSC Puzzle 2021: writeups/sysu_msc_puzzle.md
      - USTC Hackergame 2021: writeups/hackergame2021.md
      - 第四届“安洵杯”: writeups/d0g3.md
      - ByteCTF 2021 Final: writeups/bytectf2021_final.md
      - SCTF 2021: writeups/sctf2021.md
    - "2022":
      - VNCTF 2022: writeups/vnctf2022.md
      - TQLCTF 2022: writeups/tqlctf2022.md
      - SUSCTF 2022: writeups/susctf2022.md
      - D3CTF 2022: writeups/d3ctf2022.md
      - "*CTF 2022": writeups/*ctf2022.md
      - MRCTF 2022: writeups/mrctf2022.md
  - Miscellaneous:
    - misc/index.md
    - 课程笔记: misc/notes.md
    - mkdocs: misc/mkdocs.md
    - hexo: misc/hexo.md
    - sphinx: misc/sphinx.md
