site_name: 鹤翔万里的笔记本

theme: 
  name: 'material'
  language: 'zh'
  features:
    - navigation.tracking # 在url中使用标题定位锚点
    - navigation.tabs
    - navigation.sections # nav节点缩进
    # - navigation.expand # 不折叠左侧nav节点
    - navigation.top # 一键回顶部
  font:
    text: JetBrains Mono
    code: JetBrains Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist

nav:
  - Home:
    - HomePage: index.md
    - TODO: todo.md
  - CTF:
    - QRCode: CTF/qrcode.md

