site_name: 鹤翔万里的笔记本
site_url: https://note.tonycrane.cc/
repo_url: https://github.com/TonyCrane/note/
edit_uri: tree/master/docs
site_description: 鹤翔万里（TonyCrane）的笔记本
copyright: Copyright &copy; 2022 <a href="https://github.com/TonyCrane"  target="_blank" rel="noopener">TonyCrane</a>

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  palette:
    - scheme: default

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TonyCrane/
    - icon: fontawesome/solid/rss
      link: https://blog.tonycrane.cc/
    - icon: fontawesome/solid/home
      link: https://tonycrane.cc/
  analytics:
    provider: custom
    property: G-DYETCPM289

extra_css:
  - https://fastly.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - css/tasklist.css
  - css/custom.css

extra_javascript:
  - https://fastly.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - js/katex.js
  # js/scheme.js # this is in template 'base.html'

plugins:
  - rss
  - search
  - encryptcontent:  # now just for one page, need to be improved
      title_prefix: "🔒 "
      summary: '🔒 AAA School Bus Writeups'
      placeholder: '在此输入密码     '
      decryption_failure_message: '密码错误'
      encryption_info_message: '请输入密码查看本篇文章（请联系我）'
      remember_password: True 
      default_expire_dalay: 48
      encrypted_something:
        mkdocs-encrypted-toc: [nav, class]
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true

nav:
  - Home:
    - index.md
  - Computer Science:
    - cs/index.md
    - Programming Language:
      - cs/pl/index.md
      - C/C++: cs/pl/c_cpp.md
      - Haskell: cs/pl/haskell.md
      - Assembly: cs/pl/asm.md
    - Computer System:
      - cs/system/index.md
      - Computer System I:
        - cs/system/cs1/index.md
        - Number Representations: cs/system/cs1/topic1.md
        - Digital Logic: cs/system/cs1/topic2.md
    - Web:
      - cs/web/index.md
      - SVG: cs/web/svg.md
    - RegEx: cs/regex.md
    - Unicode: cs/unicode.md
  - CTF:
    - ctf/index.md
    - Steganography:
      - ctf/steg/index.md
      - Image Steganography: ctf/steg/image.md
      - Audio Steganography: ctf/steg/audio.md
    - Sandbox Escapes: 
      - ctf/escapes/index.md
      - Python Sandbox Escape: ctf/escapes/pysandbox.md
    - Coding & Cipher: ctf/coding.md
    - QRCode: ctf/qrcode.md
    - Esolang: ctf/esolang.md
  - Writeups:
    - writeups/index.md
    - Training:
      - Ethernaut: writeups/ethernaut.md
      - Security Innovation: writeups/SecurityInnovation.md
      - AAA School Bus: writeups/AAA.md
    - "2021":
      - SYSU MSC Puzzle 2021: writeups/sysu_msc_puzzle.md
      - USTC Hackergame 2021: writeups/hackergame2021.md
      - 第四届“安洵杯”: writeups/d0g3.md
      - ByteCTF 2021 Final: writeups/bytectf2021_final.md
      - SCTF 2021: writeups/sctf2021.md
    - "2022":
      - VNCTF 2022: writeups/vnctf2022.md
      - TQLCTF 2022: writeups/tqlctf2022.md
      - SUSCTF 2022: writeups/susctf2022.md
      - D3CTF 2022: writeups/d3ctf2022.md
      - "*CTF 2022": writeups/*ctf2022.md
      - MRCTF 2022: writeups/mrctf2022.md
  - Miscellaneous:
    - misc/index.md
    - mkdocs: misc/mkdocs.md
    - hexo: misc/hexo.md
    - sphinx: misc/sphinx.md
