name: Deploy Docs

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fixes shallow clone issue

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-latex-extra fonts-freefont-o

      - name: Create cache directory
        run: mkdir -p docs/_tikz_cache  # Adjust path if configured differently
      
      - name: Set up depencies
        run: pip install rich mkdocs-toolchain/mkdocs mkdocs-toolchain/mkdocs-encryptcontent-plugin mkdocs-toolchain/mkdocs-git-revision-date-localized-plugin mkdocs-toolchain/mkdocs-linkbackward-plugin mkdocs-toolchain/mkdocs-rss-plugin mkdocs-toolchain/mkdocs-tikzautomata-plugin mkdocs-toolchain/mkdocs-toc-plugin mkdocs-material==8.1.4 mkdocs-glightbox==0.3.4 mkdocs-changelog-plugin mkdocs-heti-plugin mkdocs-statistics-plugin

      - name: Build the site
        run: mkdocs build --site-dir ./site

      # 新增创建 CNAME 文件的步骤（在此处替换你的域名）
      - name: Add CNAME file
        run: |
          echo "test.foreverhyx.top" > ./site/CNAME
        # 如果域名需要保密，可以用 secret 替代：
        # echo ${{ secrets.CNAME_DOMAIN }} > ./site/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: true
